name: 'analytics'
version: '1.0.0'
config-version: 2

profile: 'analytics' # Must match the top-level name in profiles.yml

model-paths: ["models"]

models:
  analytics: # Match the 'name' of the project above
    staging:
      +schema: staging
      +materialized: table  # Fast for 8GB VPS
    analytics:
      +schema: analytics
      +materialized: table # Final clean tables for Superset