events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;


    # client_max_body_size 500M; # Crucial for large CSVs

    server {
        listen 80;
        server_name localhost;

        # This points to your docker/www/ folder (as mapped in compose)
        root /usr/share/nginx/html;
        index index.html;

        # 1. Try to serve the landing page files first
        location / {
            try_files $uri $uri/ =404;
        }

        # 2. Keep your Superset Proxy (adjust the path if needed)
        # If you want Superset at localhost/superset/
        location /superset/ {
            proxy_pass http://superset:8088/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. Optional: Proxy to Airflow if you want it under one URL
        location /airflow/ {
            # Using a variable prevents Nginx from crashing if airflow is down at startup
            set $upstream_airflow airflow;
            proxy_pass http://$upstream_airflow:8080/;
            proxy_set_header Host $host;
        }

        # File Upload API
        location /api/upload {
            proxy_pass http://upload-api:5000/upload;
            
            # --- ADD THESE THREE LINES ---
            proxy_request_buffering off;
            proxy_http_version 1.1;
            client_max_body_size 500M; 
            # -----------------------------

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /status {
            proxy_pass http://docker-status:9000/status;
        }

        location /service/ {
            proxy_pass http://docker-status:9000/service/;
        }

        
    }
}